name: llab
channels:
 - conda-forge
 - bioconda
 - defaults

dependencies:
# - bioconda::gcnvkernel
 - bioconda::rtg-tools=3.11
 - bioconda::ngs-bits
 - bioconda::vt
 - bioconda::bcftools=1.9
 - pybedtools
 - pysam
 - bwa=0.7.15
 - samblaster=0.1.24
 - sambamba=0.7.1
 - ensembl-vep=95.1
 - genesplicer=1.0
# - conda-forge::python=3.7.3
 - bioconda::fastqc=0.11.8
 - bioconda::multiqc=1.6
 - font-ttf-dejavu-sans-mono=2.37 #for FastQC
 - fontconfig=2.12.6 #for FastQC
 - freebayes=1.3.2
# gatk dependcies such as r
 - r-data.table
 - r-gplots
 - r-ggplot2
 - r-gsalib
 - r-optparse
 - r-reshape
 - gatk4=4.1.8.0
 - htslib=1.9
# - igvtools=2.3.93
 - manta=1.6.0
 - tiddit=2.11.0
#- multiqc=1.6
 - qualimap=2.2.2b
 - samtools=1.8
 - snpeff=4.3
 - strelka=2.9.3
 - vcfanno=0.3.2
 - vcftools=0.1.16
 - gvcftools
 - hap.py=0.3.12
 - peddy=0.4.6
# CNVKit
 - cnvkit
# Start of dependencies for pathoscore
 - scikit-learn
 - matplotlib
 - numpy
 - cyvcf2
 - seaborn
 - toolshed
# End of pathoscore dependencies
# Gemini